repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^tests/fixtures/diffs/
-   repo: local
    hooks:
    -   id: tests
        name: tests
        entry: pytest -v
        language: system
        pass_filenames: false
        types: [python]
        stages: [push]
